server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC
    username: niuniu
    password: louis
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka



#  cloud:
#    nacos:
#      server-addr: nacos:8848 # nacos服务地址
##      discovery:
##        namespace: 4d6ce343-9e1b-44df-a90f-2cf2b6b3d177 # dev环境
##        ephemeral: false # 是否是临时实例

#logging:
#  level:
#    cn.itcast: debug
#  pattern:
#    dateformat: MM-dd HH:mm:ss:SSS
##eureka:
##  client:
##    service-url:  # eureka的地址信息
##      defaultZone: http://127.0.0.1:10086/eureka
#userservice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则
#ribbon:
#  eager-load:
#    enabled: true # 开启饥饿加载
#    clients: # 指定饥饿加载的服务名称
#      - userservice
#feign:
#  httpclient:
#    enabled: true # 支持HttpClient的开关
#    max-connections: 200 # 最大连接数
#    max-connections-per-route: 50 # 单个路径的最大连接数
ribbon:
  eager-load:
    clients:
      - userservice
    enabled: true
